name: android_signature
description: Android signature provider for Flutter.
version: 0.0.1
homepage: https://github.com/WangYng
repository: https://github.com/WangYng/android_signature

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.github.wangyng.android_signature
        pluginClass: AndroidSignaturePlugin
      ios:
        pluginClass: AndroidSignaturePlugin
